definitions:
  common.baseResponse:
    properties:
      data: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
  controller.deleteBookmarkRequest:
    properties:
      anime_id:
        type: integer
      user_token:
        type: string
    required:
    - anime_id
    - user_token
    type: object
  controller.refreshTokenResponse:
    properties:
      auth_token:
        type: string
    type: object
  controller.saveBookmarkRequest:
    properties:
      anime_id:
        type: integer
      latest_episode:
        type: string
      user_token:
        type: string
    required:
    - anime_id
    - latest_episode
    - user_token
    type: object
  controller.syncAnimeRequest:
    properties:
      anime_ids:
        items:
          type: integer
        type: array
    required:
    - anime_ids
    type: object
  controller.videoURLRequest:
    properties:
      episode_endpoint:
        example: /naruto-episode-1
        type: string
    required:
    - episode_endpoint
    type: object
  controller.videoURLResponse:
    properties:
      video_url:
        type: string
    type: object
  domain.Anime:
    properties:
      airing_year:
        type: string
      episodes:
        items:
          $ref: '#/definitions/domain.Episode'
        type: array
      genre:
        type: string
      id:
        type: integer
      image_url:
        type: string
      latest_episode:
        type: string
      status:
        type: string
      summary:
        type: string
      title:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
  domain.Episode:
    properties:
      endpoint:
        type: string
      text:
        type: string
    type: object
  domain.RecentAnime:
    properties:
      id:
        type: integer
      image_url:
        type: string
      latest_episode:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  domain.SyncAnime:
    properties:
      id:
        type: integer
      latest_episode:
        type: string
      updated_at:
        type: string
    type: object
  webscraper.TitleSearchResult:
    properties:
      endpoint:
        example: /category/naruto
        type: string
      title:
        example: naruto
        type: string
    required:
    - endpoint
    - title
    type: object
info:
  contact: {}
paths:
  /anime/detail-alt:
    post:
      description: This endpoint will scrape the detail instead of fetching from database
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/webscraper.TitleSearchResult'
      - default: Bearer <Add access token here>
        description: Insert your auth token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.baseResponse'
            - properties:
                data:
                  $ref: '#/definitions/domain.Anime'
              type: object
      summary: Anime detail alternative
      tags:
      - Anime
  /anime/detail/{anime_id}:
    get:
      description: By providing anime id, this endpoint will return the details
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your auth token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Anime ID
        in: path
        name: anime_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.baseResponse'
            - properties:
                data:
                  $ref: '#/definitions/domain.Anime'
              type: object
      summary: Get anime detail
      tags:
      - Anime
  /anime/recent:
    get:
      description: This endpoint supports pagination
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your auth token
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1
        description: Desired page
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.baseResponse'
            - properties:
                data:
                  $ref: '#/definitions/domain.RecentAnime'
              type: object
      summary: Get recently updated / released anime
      tags:
      - Anime
  /anime/search:
    get:
      description: Will find all anime with matching keywords
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your auth token
        in: header
        name: Authorization
        required: true
        type: string
      - default: Naruto
        description: Keywords of anime title
        in: query
        name: keywords
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.baseResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/webscraper.TitleSearchResult'
                  type: array
              type: object
      summary: Search anime title
      tags:
      - Anime
  /anime/sync:
    post:
      description: To sync anime data from client to server
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.syncAnimeRequest'
      - default: Bearer <Add access token here>
        description: Insert your auth token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.baseResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/domain.SyncAnime'
                  type: array
              type: object
      summary: Sync anime
      tags:
      - Anime
  /anime/video-url:
    post:
      description: Fetch video URL by episode endpoint
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.videoURLRequest'
      - default: Bearer <Add access token here>
        description: Insert your auth token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.baseResponse'
            - properties:
                data:
                  $ref: '#/definitions/controller.videoURLResponse'
              type: object
      summary: Video URL
      tags:
      - Anime
  /bookmark:
    delete:
      description: User can delete bookmark to opt out from notification in the future
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.deleteBookmarkRequest'
      - default: Bearer <Add access token here>
        description: Insert your auth token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.baseResponse'
      summary: Delete bookmark
      tags:
      - Bookmark
    post:
      description: User can receive notification from apps when their bookmarked anime
        has new update
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.saveBookmarkRequest'
      - default: Bearer <Add access token here>
        description: Insert your auth token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.baseResponse'
      summary: Save bookmark
      tags:
      - Bookmark
  /token/refresh:
    get:
      description: Refresh token will have later expiry date than auth token so user
        can reissue auth token whenever expired
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your refresh token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.baseResponse'
            - properties:
                data:
                  $ref: '#/definitions/controller.refreshTokenResponse'
              type: object
      summary: Generate auth token by providing refresh token
      tags:
      - Token
swagger: "2.0"
