name: deploy 2nd half service

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
# Set environment variables 
env:
  RAILWAY_TOKEN: ${{ secrets.SECRET_SECOND_TOKEN }}
  RAILWAY_PROJECT_ID: ${{ secrets.PROJECT_SECOND_ID }}
  RAILWAY_SERVICE_NAME: ${{ secrets.SERVICE_SECOND_NAME }}

jobs:

  unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:

    # Checkout branch
    - name: Checkout
      uses: actions/checkout@v2.4.2

    # Setup go environment and add it to PATH
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    # Test all available tests
    - name: Testing
      run: go test ./...
      
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: unit_test
    steps:

    # Checkout branch
    - name: Checkout
      uses: actions/checkout@v2

    - name: Alter values with sed
      run: |
        sed -i "s|url1placeholder|${{ secrets.URL_1 }}|g" ./urls.txt
        sed -i "s|url2placeholder|${{ secrets.URL_2 }}|g" ./urls.txt
        sed -i "s|versionplaceholder|1|g" .env

    # Deploy
    - name: Deployment
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        railway up --service=$RAILWAY_SERVICE_NAME